---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: leptopoda-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42 # latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship

    remove:
      - firefox
      - firefox-langpacks

  - type: dnf
    install:
      packages:
        - podman

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        # bluefin dx
        - io.podman_desktop.PodmanDesktop
        - io.github.getnf.embellish
        - me.iepure.devtoolbox
        - sh.loft.devpod
        # bluefin
        - io.github.dvlv.boxbuddyrs
        - com.github.rafostar.Clapper
        - com.mattjakeman.ExtensionManager
        - com.github.tchx84.Flatseal
        - com.github.PintaProject.Pinta
        - io.github.flattool.Ignition
        - io.github.flattool.Warehouse
        - io.gitlab.adhami3310.Impression
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.DejaDup
        - org.gnome.Papers
        - org.gnome.FileRoller
        - org.gnome.Firmware
        - org.gnome.font-viewer
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.NautilusPreviewer
        - org.gnome.SimpleScan
        - org.gnome.TextEditor
        - org.gnome.Weather
        - io.missioncenter.MissionCenter
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
        - page.tesk.Refine
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
      remove:
        - org.gnome.eog
    user: {}

  - type: signing

