---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: leptopoda-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42 # latest

modules:
  - from-file: common_modules/files.yml
  - type: signing
