---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: leptopoda-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/aurora-dx # ghcr.io/ublue-os/kinoite-main
image-version: stable

modules:
  - from-file: common_modules/files.yml
  - from-file: common_modules/dnf.yml
  - from-file: common_modules/default-flatpaks.yml
  - type: signing
