---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: leptopoda-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42 # latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      # bluefin all all
      - adcli
      - adw-gtk3-theme
      - bash-color-prompt
      - bcache-tools
      - bluefin-backgrounds
      - bluefin-cli-logos
      - bluefin-faces
      - bluefin-fastfetch
      - bluefin-schemas
      - bootc
      - borgbackup
      - cryfs
      - ddcutil
      - evtest
      - fastfetch
      - firewall-config
      - fish
      - foo2zjs
      - fuse-encfs
      - gcc
      - git-credential-libsecret
      - glow
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-logo-menu
      - gnome-shell-extension-search-light
      - gnome-shell-extension-tailscale-gnome-qs
      - gnome-tweaks
      - gum
      - hplip
      - ibus-mozc
      - ifuse
      - input-remapper
      - iwd
      - jetbrains-mono-fonts-all
      - krb5-workstation
      - libgda
      - libgda-sqlite
      - libimobiledevice
      - libratbag-ratbagd
      - libsss_autofs
      - libxcrypt-compat
      - lm_sensors
      - make
      - mesa-libGLU
      - mozc
      - nautilus-gsconnect
      - nerd-fonts
      - oddjob-mkhomedir
      - opendyslexic-fonts
      - openssh-askpass
      - powertop
      - printer-driver-brlaser
      - pulseaudio-utils
      - python3-pip
      - python3-pygit2
      - rclone
      - restic
      - samba
      - samba-dcerpc
      - samba-ldb-ldap-modules
      - samba-winbind-clients
      - samba-winbind-modules
      - setools-console
      - sssd-ad
      - sssd-krb5
      - sssd-nfs-idmap
      - tailscale
      - tmux
      - ublue-bling
      - ublue-brew
      - ublue-fastfetch
      - ublue-motd
      - ublue-polkit-rules
      - ublue-setup-services
      - uld
      - usbmuxd
      - wireguard-tools
      - wl-clipboard
      - xprop
      - yaru-theme
      - zenity
      - zsh
      # bluefin all dx
      - adobe-source-code-pro-fonts
      - android-tools
      - bcc
      - bpftop
      - bpftrace
      - cascadia-code-fonts
      - cockpit-bridge
      - cockpit-machines
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
      - code
      - containerd.io
      - dbus-x11
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - edk2-ovmf
      - flatpak-builder
      - genisoimage
      - google-droid-sans-mono-fonts
      - google-go-mono-fonts
      - ibm-plex-mono-fonts
      - incus
      - incus-agent
      - iotop
      - kcli
      - libvirt
      - libvirt-nss
      - lxc
      - mozilla-fira-mono-fonts
      - nicstat
      - numactl
      - osbuild-selinux
      - p7zip
      - p7zip-plugins
      - podman-bootc
      - podman-compose
      - podman-machine
      - podman-tui
      - podmansh
      - powerline-fonts
      - python3-ramalama
      - qemu
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - rocm-hip
      - rocm-opencl
      - rocm-smi
      - sysprof
      - tiptop
      - trace-cmd
      - ubuntu-family-fonts
      - udica
      - umoci
      - virt-manager
      - virt-v2v
      - virt-viewer
      - ydotool
      # bluefin 42 all
      - bazaar
      - google-noto-fonts-all
      - uupd

    remove:
      - firefox
      - firefox-langpacks

  - type: dnf
    # repos:
    #   copr:
    #     - atim/starship
    #     - trixieua/mutter-patched
    install:
      packages:
        # bluefin all all
        - adcli
        - adw-gtk3-theme
        - bash-color-prompt
        - bcache-tools
        - bluefin-backgrounds
        - bluefin-cli-logos
        - bluefin-faces
        - bluefin-fastfetch
        - bluefin-schemas
        - bootc
        - borgbackup
        - cryfs
        - ddcutil
        - evtest
        - fastfetch
        - firewall-config
        - fish
        - foo2zjs
        - fuse-encfs
        - gcc
        - git-credential-libsecret
        - glow
        - gnome-shell-extension-appindicator
        - gnome-shell-extension-blur-my-shell
        - gnome-shell-extension-caffeine
        - gnome-shell-extension-dash-to-dock
        - gnome-shell-extension-gsconnect
        - gnome-shell-extension-logo-menu
        - gnome-shell-extension-search-light
        - gnome-shell-extension-tailscale-gnome-qs
        - gnome-tweaks
        - gum
        - hplip
        - ibus-mozc
        - ifuse
        - input-remapper
        - iwd
        - jetbrains-mono-fonts-all
        - krb5-workstation
        - libgda
        - libgda-sqlite
        - libimobiledevice
        - libratbag-ratbagd
        - libsss_autofs
        - libxcrypt-compat
        - lm_sensors
        - make
        - mesa-libGLU
        - mozc
        - nautilus-gsconnect
        - nerd-fonts
        - oddjob-mkhomedir
        - opendyslexic-fonts
        - openssh-askpass
        - powertop
        - printer-driver-brlaser
        - pulseaudio-utils
        - python3-pip
        - python3-pygit2
        - rclone
        - restic
        - samba
        - samba-dcerpc
        - samba-ldb-ldap-modules
        - samba-winbind-clients
        - samba-winbind-modules
        - setools-console
        - sssd-ad
        - sssd-krb5
        - sssd-nfs-idmap
        - tailscale
        - tmux
        - ublue-bling
        - ublue-brew
        - ublue-fastfetch
        - ublue-motd
        - ublue-polkit-rules
        - ublue-setup-services
        - uld
        - usbmuxd
        - wireguard-tools
        - wl-clipboard
        - xprop
        - yaru-theme
        - zenity
        - zsh
        # bluefin all dx
        - adobe-source-code-pro-fonts
        - android-tools
        - bcc
        - bpftop
        - bpftrace
        - cascadia-code-fonts
        - cockpit-bridge
        - cockpit-machines
        - cockpit-networkmanager
        - cockpit-ostree
        - cockpit-podman
        - cockpit-selinux
        - cockpit-storaged
        - cockpit-system
        - code
        - containerd.io
        - dbus-x11
        - docker-buildx-plugin
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - edk2-ovmf
        - flatpak-builder
        - genisoimage
        - google-droid-sans-mono-fonts
        - google-go-mono-fonts
        - ibm-plex-mono-fonts
        - incus
        - incus-agent
        - iotop
        - kcli
        - libvirt
        - libvirt-nss
        - lxc
        - mozilla-fira-mono-fonts
        - nicstat
        - numactl
        - osbuild-selinux
        - p7zip
        - p7zip-plugins
        - podman-bootc
        - podman-compose
        - podman-machine
        - podman-tui
        - podmansh
        - powerline-fonts
        - python3-ramalama
        - qemu
        - qemu-char-spice
        - qemu-device-display-virtio-gpu
        - qemu-device-display-virtio-vga
        - qemu-device-usb-redirect
        - qemu-img
        - qemu-system-x86-core
        - qemu-user-binfmt
        - qemu-user-static
        - rocm-hip
        - rocm-opencl
        - rocm-smi
        - sysprof
        - tiptop
        - trace-cmd
        - ubuntu-family-fonts
        - udica
        - umoci
        - virt-manager
        - virt-v2v
        - virt-viewer
        - ydotool
        # bluefin 42 all
        - bazaar
        - google-noto-fonts-all
        - 

  #- type: dnf
  #  remove:
  #    packages:
  #      # bluefin all all
  #      - fedora-bookmarks
  #      - fedora-chromium-config
  #      - fedora-chromium-config-gnome
  #      - firefox
  #      - firefox-langpacks
  #      - gnome-extensions-app
  #      - gnome-shell-extension-background-logo
  #      - gnome-software
  #      - gnome-software-rpm-ostree
  #      - gnome-terminal-nautilus
  #      - podman-docker
  #      - yelp

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        # bluefin dx
        - io.podman_desktop.PodmanDesktop
        - io.github.getnf.embellish
        - me.iepure.devtoolbox
        - sh.loft.devpod
        # bluefin
        - io.github.dvlv.boxbuddyrs
        - com.github.rafostar.Clapper
        - com.mattjakeman.ExtensionManager
        - com.github.tchx84.Flatseal
        - com.github.PintaProject.Pinta
        - io.github.flattool.Ignition
        - io.github.flattool.Warehouse
        - io.gitlab.adhami3310.Impression
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.DejaDup
        - org.gnome.Papers
        - org.gnome.FileRoller
        - org.gnome.Firmware
        - org.gnome.font-viewer
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.NautilusPreviewer
        - org.gnome.SimpleScan
        - org.gnome.TextEditor
        - org.gnome.Weather
        - io.missioncenter.MissionCenter
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
        - page.tesk.Refine
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
      remove:
        - org.gnome.eog
    user: {}

  - type: signing

