---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: leptopoda-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main # ghcr.io/ublue-os/bluefin-dx
image-version: 42 # latest

modules:
  - from-file: common_modules/files.yml
  # - from-file: common_modules/akmods.yml
  # - from-file: common_modules/bling.yml
  - from-file: common_modules/chezmoi.yml
  - from-file: common_modules/default-flatpaks.yml
  - from-file: common_modules/fonts.yml
  - from-file: common_modules/gschema-overrides.yml
  - from-file: common_modules/rpm-ostree.yml
  - from-file: common_modules/rpm-ostree-gnome.yml
  #- from-file: common_modules/dnf.yml
  #- from-file: common_modules/dnf-gnome.yml
  #- from-file: common_modules/yafti.yml
  - from-file: common_modules/systemd.yml
  - from-file: common_modules/script.yml
  - from-file: common_modules/containerfile.yml
  - type: signing
